markdown: redcarpet
highlighter: null
permalink: /:title

url: http://www.sheix.info/
baseurl: http://sheix.github.io/

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
