markdown: redcarpet
highlighter: pygments
permalink: /:title

url: http://www.sheix.info/
baseurl: 

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
